### ISSUE TITLE
adding "-drop" layer throws error

### ISSUE THREAD

**Issue by kikaxa** [hughperkins/DeepCL#100]
>Something went wrong: need to copyToDevice() before calling kernel->input

to anything as simple as "netdef=10n-elu-100n-elu-51n" -> "netdef=10n-drop-elu-100n-elu-51n"
it gives the same error regardless of the place i insert "-drop" into.

input is 32x32,
deepcl-win64-v11.3.1, iris pro 5200, win7

[log.txt](https://github.com/hughperkins/DeepCL/files/568947/log.txt)

**Comment by kikaxa** [comment]
it might be in DropoutForward::forward for outputWrapper?
i'll check it later

**Comment by hughperkins** [comment]
Cool, thanks! :-)
