### ISSUE TITLE
any interest in batch normalization(train) / input renormalization(predict) ?

### ISSUE THREAD

**Issue by kikaxa** [hughperkins/DeepCL#108]
i have some working code in my tree
(https://github.com/kikaxa/DeepCL/commit/392acabcacdca84c1591720da2d7a23629f52994 and later)

basically, this adds flag for per-batch normalization in training, 
and flag to update normalization on whole input on prediction. 
(good if you predict big enough number of  new samples at once)

in my tests, this slightly reduces errors for similar but not trained on samples.
this patch only handles some of the possible input configurations(e.g. on-demand/non-stdio)

is there any interest in merging this?

**Comment by hughperkins** [comment]
Sorry, I was distracted doing other things.  I should probably merge a PR from your on this. In the meantime, I kind of need a batch normalization layer in [coriander](https://github.com/hughperkins/coriander). Thoughts?
