### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by skn123** [hughperkins/DeepCL#122]
A build error is appearing:

https://gist.github.com/skn123/52c8d3044c7179b05c9dfe418bab4ab1

**Comment by hughperkins** [comment]
question: any reason why you are choosing not to use one of the pre-built packages? http://deepcl.hughperkins.com/Downloads/

**Comment by skn123** [comment]
I want to build the source codes from scratch as I want to understand the API calls.

**Comment by hughperkins** [comment]
cool :-)
