### ISSUE TITLE
function "NetLearner::learn" is deprecated, how to train a network by the new method?

### ISSUE THREAD

**Issue by MiniLight** [hughperkins/DeepCL#134]
I'm trying to build a simple NN follow the API document, but maybe need some update.

https://github.com/hughperkins/DeepCL/blob/master/doc/NeuralNetAPI.md#train

https://github.com/hughperkins/DeepCL/blob/b2562203cd72112b18e9fa511a4f0d3506375200/src/batch/NetLearner.cpp#L148

**Comment by hughperkins** [comment]
Using the `tickXXX` methods, eg something like: https://github.com/hughperkins/DeepCL/blob/b2562203cd72112b18e9fa511a4f0d3506375200/src/main/train.cpp#L388

```
    netLearner->reset();
    while(!netLearner->isLearningDone()) {
        netLearner->tickBatch();
        if(netLearner->getEpochDone()) {
            // ...
        }
   }
```

**Comment by MiniLight** [comment]
it's working, thanks.
