### ISSUE TITLE
deepcl_unittests not running in CentOS 7.

### ISSUE THREAD

**Issue by prabhaaharan** [hughperkins/DeepCL#150]
As per installation procedure. I downloaded deepcl package and activated it. But when i try to run deepcl_unittests it throws like this. 
`deepcl_unittests: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory`

In my centos I have libjpeg files in /usr/lib64/ as
`lrwxrwxrwx.  1 root root       17 Mar  6 15:28 libjpeg.so -> libjpeg.so.62.1.0`
`lrwxrwxrwx.  1 root root       17 Jan 30 18:18 libjpeg.so.62 -> libjpeg.so.62.1.0`
`-rwxr-xr-x.  1 root root   285408 Oct 30 22:45 libjpeg.so.62.1.0`

I tried changing DeepCLTargets.cmake file 
from 
`IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "EasyCL;clBLAS;/usr/lib/x86_64-linux-gnu/libjpeg.so`
to 
`IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "EasyCL;clBLAS;/usr/lib64/libjpeg.so`

But no change. Please help me out.

**Comment by acharles7** [comment]
You need to download libjpeg.so.8 shared library and place it in dist/lib/ 
you can find this shared library from: https://github.com/maciej-c/libjpeg8x64

**Comment by prabhaaharan** [comment]
Thanks. Now working fine
