### ISSUE TITLE
Hook for model serialization

### ISSUE THREAD

**Issue by RyanHope** [hughperkins/DeepCL#26]
I've modified your qlearning example to play tetris and all is fine and dandy but it would be nice to save the net somehow so that I can resume training or use the trained net in another application. Are there any entry points in the current API for doing this or do I need to write something my self?

**Comment by hughperkins** [comment]
Hi Ryan, you can use [WeightsPersister](https://github.com/hughperkins/DeepCL/blob/master/src/weights/WeightsPersister.h) class to persist the weights.  You can see an example of loading the weights at https://github.com/hughperkins/DeepCL/blob/master/src/main/train.cpp#L329 , and saving the weights at https://github.com/hughperkins/DeepCL/blob/master/src/main/train.cpp#L386

**Comment by hughperkins** [comment]
Closing this since old.  If I haven't quite addressed your question, please go ahead and reopen :-)
