### ISSUE TITLE
Replacing InputMaker with InputLayerMaker

### ISSUE THREAD

**Issue by magedahmed** [hughperkins/DeepCL#36]
This line from the NN API:
    
    net->addLayer(InputLayerMaker::instance()->numPlanes(1)->imageSize(28));

Causes the compilation error:

    nn.cpp: In function 'int main()':
    nn.cpp:11:19: error: incomplete type 'InputMaker' used in nested name specifier
      net->addLayer(InputMaker::instance()->numPlanes(1)->imageSize(28));
                   ^
Following the code in the test files though ([testsimpleconvolvenet.cpp#L236](https://github.com/hughperkins/DeepCL/blob/6710b38eac664a53242d777d49ff740821273a3a/test/testsimpleconvolvenet.cpp#L236)), and using `InputLayerMaker`, compilation succeeds

    net->addLayer(InputLayerMaker::instance()->numPlanes(1)->imageSize(28));

Should the docs be changed to use `InputLayerMaker` instead of `InputMaker`, or is my library linking incorrect?

Thanks

**Comment by hughperkins** [comment]
Thanks! Addressed in b2a6c58

**Comment by magedahmed** [comment]
Thanks!
