### ISSUE TITLE
Where/How to start reading csv data?

### ISSUE THREAD

**Issue by mbPDWTeSe33** [hughperkins/DeepCL#48]
Hi,
my problem data is available in CSV format. I have no documentation found how to load this data. Also, I was wondering no one else has requested this feature.
As a developer, I would simply add a custom Loader class.
Maybe it's worth it for someone else, so it should follow your guidelines. After all I would send it as pull request.

**Comment by mbPDWTeSe33** [comment]
Using python this request is not trashy.

**Comment by hughperkins** [comment]
Ok, you're saying, using python, no longer need this request?
