### ISSUE TITLE
Adapt DeepCL to be able for replacing cuDNN in caffe

### ISSUE THREAD

**Issue by inferrna** [hughperkins/DeepCL#53]
There is at least two tries to make [caffe](https://github.com/BVLC/caffe) using OpenCL 
https://github.com/naibaf7/caffe
https://github.com/lunochod/caffe

Now caffe focused on using CUDA as GPU backend. In addition to own *.cu code it uses NVIDIA's proprietary cuDNN library, which is similar to DeepCL (at least by destination and realized layers). Would you please thinking about to do some job to make some kind of wrapper which can be cuDNN replacement for caffe?

**Comment by hughperkins** [comment]
I think caffe has enough opencl implementations for now ;-)  Fabian, Robert and Junli have done excellent jobs on creating opencl implementations for caffe.  The open challenge for caffe opencl is not so much technical implementation, as these already exist, as stated, so much as merging to master.

In the meantime all the available caffe forks are, according to my understanding, perfectly usable, right now, without being merged to master.

=> closing this issue.
