### ISSUE TITLE
Install on mac (el capitan)

### ISSUE THREAD

**Issue by areeberg** [hughperkins/DeepCL#56]
Hello, 
Is there any tutorial on how to install it on mac and run with XCode? It could be very helpful.
If I install it correctly, I can make an tutorial, but for now I can't help very much. 
Thank you.

**Comment by Dexdev08** [comment]
You should read the thread in this issue.

You can also try reading the summary below.

http://mynotebookis.blogspot.com/2015/11/installing-deepcl-on-macbook-air-2013.html?m=1

**Comment by hughperkins** [comment]
Thank you Dexdev08, that looks really useful :-)

Alexandre, just in case you want to convince yourself that DeepCL really does build and run on Mac OS X, note that there is a travis build at https://travis-ci.org/hughperkins/DeepCL/builds eg https://travis-ci.org/hughperkins/DeepCL/builds/115280480  This runs the travis file at https://github.com/hughperkins/DeepCL/blob/master/.travis.yml

**Comment by areeberg** [comment]
Hello Hugh, I’m sorry to bother you again, but I was able to install correctly your CNN library, but I have some questions, and I hope you can help me. - Is it any way to use it with XCode and c++? - I didn’t find any .cl code, so how can I manage task relation between CPU-GPU? For last, you did a great job for the deep learning community, thank you!
Alexandre Reeberg de Mello areeberg@gmail.com
via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.6.18&pv=10.11.4&source=email_footer_2]
On sex, mar 11, 2016 at 7:22 AM, Hugh Perkins <notifications@github.com> wrote:
Thank you Dexdev08, that looks really useful :-)

Alexandre, just in case you want to convince yourself that DeepCL really does build and run on Mac OS X, note that there is a travis build at https://travis-ci.org/hughperkins/DeepCL/builds [https://travis-ci.org/hughperkins/DeepCL/builds] eg https://travis-ci.org/hughperkins/DeepCL/builds/115280480 [https://travis-ci.org/hughperkins/DeepCL/builds/115280480] This runs the travis file at https://github.com/hughperkins/DeepCL/blob/master/.travis.yml [https://github.com/hughperkins/DeepCL/blob/master/.travis.yml]

**Comment by hughperkins** [comment]
I'm not sure I understand your question
- 'I didn’t find any .cl code'  It's in cl folder, https://github.com/hughperkins/DeepCL/tree/master/cl
- 'Is it any way to use it with XCode and c++?'  It builds on Mac OS X, see https://travis-ci.org/hughperkins/DeepCL/builds/118806956
  - to use DeepCL from C++, see https://github.com/hughperkins/DeepCL/blob/master/doc/NeuralNetAPI.md
- how can I manage task relation between CPU-GPU
  - DeepCL only handles training on the GPU, but you can prepare the data you want on the cpu / main-memory, then simply pass it into DeepCL as a float array, and the results will appear at the other end of the, also as a normal float array.  DeepCL handles pumping your data to and from the GPU for you

**Comment by Dexdev08** [comment]
I think what alexandre is asking if he can use deepcl in obj-c /c++... I
dont really use xcode.

But there is a c++ library so one should be able to use it for c++.

**Comment by areeberg** [comment]
Hello Hugh, I’m trying to compile your example on XCode with C++ because I’ll develop my PhD project integrating CNN with other techniques. However I’m having troubles to do it. I followed your instructions to install and almost everything was ok, with the exception of inverting the lines $ pip install wheel and $ pip install numpy. At the end, the answer was:[----------] Global test environment tear-down

[==========] 176 tests from 37 test cases ran. (191542 ms total)

[ PASSED ] 171 tests.

[ FAILED ] 5 tests, listed below:

[ FAILED ] SLOW_testforward.compare_args

[ FAILED ] SLOW_testforward.perf_kgsgo_64c7_args

[ FAILED ] SLOW_testbackward.perf_kgsgo_32c5

[ FAILED ] SLOW_testNorbLoader.loadall

[ FAILED ] DATA_testNorbLoader.load1000




5 FAILED TESTS

YOU HAVE 2 DISABLED TESTS




This way I taught, probably those errors are related to some specific library, as the Norb dataset. Next step was trying to use it from Xcode. I created a new C++ project, added OpenCL framework (I already tried the opencl programming before, so it’s running), and added the header and library paths. I set the C++ language dialect to GNU 11 and C++ 11 (tried with both), and libstdc++ (GNU C++ standard library). My code is very simple, as following:#include <iostream>

#include "DeepCL.h"

#include “EasyCL.h"

int main( int argc, const char * argv[]) {

EasyCL *cl = EasyCL :: createForFirstGpuOtherwiseCpu ();

//NeuralNet *net = new NeuralNet( cl );

return 0 ;



}


But got the error #include <cstdint> file not found. I have the intention of contribute with different methods to your project. Can you help me to say what I’m doing wrong? Thank you very much again,
Alexandre Reeberg de Mello areeberg@gmail.com
via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.6.18&pv=10.11.4&source=email_footer_2]
On ter, mar 29, 2016 at 8:04 AM, Hugh Perkins <notifications@github.com> wrote:
I'm not sure I understand your question

 * 'I didn’t find any .cl code' It's in cl folder, https://github.com/hughperkins/DeepCL/tree/master/cl [https://github.com/hughperkins/DeepCL/tree/master/cl]
 * 'Is it any way to use it with XCode and c++?' It builds on Mac OS X, see https://travis-ci.org/hughperkins/DeepCL/builds/118806956 [https://travis-ci.org/hughperkins/DeepCL/builds/118806956] * to use DeepCL from C++, see https://github.com/hughperkins/DeepCL/blob/master/doc/NeuralNetAPI.md [https://github.com/hughperkins/DeepCL/blob/master/doc/NeuralNetAPI.md]
   
   
 * how can I manage task relation between CPU-GPU * DeepCL only handles training on the GPU, but you can prepare the data you want on the cpu / main-memory, then simply pass it into DeepCL as a float array, and the results will appear at the other end of the, also as a normal float array. DeepCL handles pumping your data to and from the GPU for you

**Comment by hughperkins** [comment]
for the failed tests:
- all tests prefixed SLOW_, I dont normally run, so it's not too weird if they fail.  Ignore
- all tests prefixed DATA_ need some specific dataset downloaded ,in this case norb.  Without that dataset downloaded, it's normal that it fails, so ignore.  (It's only used to test the norbloader functionality anyway, so not some fundamental test)

> I set the C++ language dialect to GNU 11 and C++ 11 (tried with both), and libstdc++ (GNU C++ standard library).

I'm using C++0x as my standard, on linux, (and Visual Studio 2010 as my standard on Windows).  I use c++0x instead of c++11x for two reasons:
- it's approximately compatible with Visual Studio 2010 (not really the case with c++11x, which has lots of surprises when I try to build on VS2010...)
- it widens the number of linux-based people who can build it too (some people are on gcc 4.4 and so on)

> #include <cstdint> file not found

You might need to google a bit to find out the equivalent on your system.  Or maybe it's simply not needed.  You could try commenting it out, and see what errors you get in its place (if any).  Then, eithre leave it commented, or replace with the equivalent `#include` for your system.  Then, we can probably add an `#ifdef` around it, so that it generalizes to build on all systems.

**Comment by areeberg** [comment]
Hello Hugh, I google about your recommendations, and here are my answers (and my new issue). About the C++0x, it was the name for the standard before it was released / finalized. Once it was finalized (in the year 2011), we were able to name it properly. That is, C++11 . This way I’m using the correct one. Then I got an error on include < cstdint>, but I found the directory of the headers ( /usr/include/c++/4.2.1). So I included #include <cstdint> in the main file. But now I’m getting error on type_traits (inside c++ folder), when using c++ standard library. The errors are in the use of undeclared identifier nullptr_t (I got 4 errors). If I try to compile with GNU, the crhono.h file is not found.
Thank you again!
Alexandre Reeberg de Mello areeberg@gmail.com
via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.6.18&pv=10.11.4&source=email_footer_2]
On ter, mar 29, 2016 at 8:30 PM, Hugh Perkins <notifications@github.com> wrote:
for the failed tests:

 * all tests prefixed SLOW_, I dont normally run, so it's not too weird if they fail. Ignore
 * all tests prefixed DATA_ need some specific dataset downloaded ,in this case norb. Without that dataset downloaded, it's normal that it fails, so ignore. (It's only used to test the norbloader functionality anyway, so not some fundamental test)

I set the C++ language dialect to GNU 11 and C++ 11 (tried with both), and libstdc++ (GNU C++ standard library).

I'm using C++0x as my standard, on linux, (and Visual Studio 2010 as my standard on Windows). I use c++0x instead of c++11x for two reasons:

 * it's approximately compatible with Visual Studio 2010 (not really the case with c++11x, which has lots of surprises when I try to build on VS2010...)
 * it widens the number of linux-based people who can build it too (some people are on gcc 4.4 and so on)

#include file not found

You might need to google a bit to find out the equivalent on your system. Or maybe it's simply not needed. You could try commenting it out, and see what errors you get in its place (if any). Then, eithre leave it commented, or replace with the equivalent #include for your system. Then, we can probably add an #ifdef around it, so that it generalizes to build on all systems.

**Comment by hughperkins** [comment]
> The errors are in the use of undeclared identifier nullptr_t (I got 4 errors). If I try to compile with GNU, the crhono.h file is not found.

Can you put full build output from both situations into gists please, and send me the gist url?  (gist is at http://gist.github.com )

**Comment by areeberg** [comment]
I comment in the first line some information about it. https://gist.github.com/areeberg/009e9473b1937b27ba5a9f45cc283722 https://gist.github.com/areeberg/31a06090dbd85ed8964ad5b947a86826

Thank you,
Alexandre Reeberg de Mello areeberg@gmail.com
via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.6.18&pv=10.11.4&source=email_footer_2]
On qua, mar 30, 2016 at 10:37 AM, Hugh Perkins <notifications@github.com> wrote:
The errors are in the use of undeclared identifier nullptr_t (I got 4 errors). If I try to compile with GNU, the crhono.h file is not found.

Can you put full build output from both situations into gists please, and send me the gist url? (gist is at http://gist.github.com [http://gist.github.com] )

**Comment by hughperkins** [comment]
k.  I kind of want to see the exact output, on your commandline.  For example, you can do:
```
make -j 4 > out.txt 2>&1
```
... and send me the contents of out.txt

**Comment by areeberg** [comment]
Hello Hugh, As I´m trying to run it with XCode, I don´t have a makefile (just a .xcodeproj).

Alexandre Reeberg de Mello areeberg@gmail.com
via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.6.18&pv=10.11.4&source=email_footer_2]
On qua, mar 30, 2016 at 12:01 PM, Hugh Perkins <notifications@github.com> wrote:
k. I kind of want to see the exact output, on your commandline. For example, you can do:

make -j 4 > out.txt 2>&1


... and send me the contents of out.txt

**Comment by hughperkins** [comment]
Ah, well, somewhere you should have some sort of compiler output.  At least, Visual Studio provides compiler output.  Can you provide me a screenshot please?

But, basically, I doubt I can help much: `chrono` library is part of the C++11 standard.  If chrono cant be loaded, then your compiler doesnt actually support C++11, and you'll need to dig a bit to find out what to use instead.  You might need to modify the (very few) classes that use chrono library, of which there are approximately two.

**Comment by hughperkins** [comment]
closing this since no recent information.  Please feel free to add additional information, and reopen :-)
