### ISSUE TITLE
CrossEntropyLoss.cpp

### ISSUE THREAD

**Issue by zeno40** [hughperkins/DeepCL#62]
Hi,

line:67       gradInput[i] = (input[i] - expectedOutput[i]) / input[i] / (1.0f - input[i]);
is this correct? In https://github.com/nyanp/tiny-cnn/blob/master/tiny_cnn/lossfunctions/loss_function.h
                 gradInput[i] = (input[i] - expectedOutput[i]) / (input[i] * (1.0f - input[i]));
is used.

thanks,
filip

**Comment by hughperkins** [comment]
the brackets are differnet, you can test eg:
```
wcalc "1 / 3 / 5"
wcalc "1 / (3*5)"
```
... will give the same answer

**Comment by zeno40** [comment]
Oh, I see, stupid of me!

**Comment by hughperkins** [comment]
:-)
