### ISSUE TITLE
Python Examples

### ISSUE THREAD

**Issue by Dexdev08** [hughperkins/DeepCL#67]
Hi Hugh,

Ive been following the gitter threads of other deeplearning frameworks and i thinj deepcl can have more examples.

Since i am going through learning deep learning what can you suggest as a starting path and i can document the process as well.

**Comment by hughperkins** [comment]
Ok. Sounds good.  How about, from the other way around: what are you trying to achieve?  I can think of some options:
- take examples you've seen from other libraries, port to DeepCL
- a specific research goal
- a specific industrial goal
