### ISSUE TITLE
Hi Hugh

### ISSUE THREAD

**Issue by latcoin** [hughperkins/DeepCL#70]
This is the only way I knew how to contact you. I'm working on a predictor algorithm for this bitcoin trading application and would love to try out a strategy using your Q-learning code. Would you have some time and/or interest in working with me on this project? I manage a decent sized fund for bitcoin trading and I'd love to partner with you on this project (if there's interest).

nharan81@gmail.com

**Comment by hughperkins** [comment]
Thanks!  I do have a full-time job right now though :-)
