### ISSUE TITLE
Requesting .NET API

### ISSUE THREAD

**Issue by merceyz** [hughperkins/DeepCL#73]
Hello,

Really interesting project and it would be awesome if there was an .NET API for it.

I'm trying to use the CMD "API" to have it learn some 96x96x3 .png images but not having much luck

**Comment by hughperkins** [comment]
.Net API... well, there's no reason why there couldnt be one.  I'm on ubuntu myself though.  I'll add a 'help wanted' label to this issue, and leave it open :-)

> I'm trying to use the CMD "API" to have it learn some 96x96x3 .png images but not having much luck

Ok.  Do you want to open a separate issue for this, and provide additional details in that, about what you are trying, what you are expecting to happen, and what actually happens?

**Comment by merceyz** [comment]
I'm assuming the easiest way would be to make a wrapper over the c++ API, that way there is no need to "rewrite" the code.

I made a new issue for my question with more information in it

**Comment by hughperkins** [comment]
Yes, wrapper over c++ api sounds like a reasonable way forward for this.  I've done stuff like that before, eg https://github.com/hughperkins/SpringRTS-CSharpAI , but I'd rather focus my effort on opencl convolution currently.
