### ISSUE TITLE
Simple example network for XOR task

### ISSUE THREAD

**Issue by d0znpp** [hughperkins/DeepCL#76]
Hi! Thx for a great job!

Can I ask you to add simple Python example without images recognition?
Smth like http://www.mind.ilstu.edu/curriculum/artificial_neural_net/xor_problem_and_solution.php

It would be great to understand library methods without documentation.

**Comment by hughperkins** [comment]
Sure.  It is here :-) https://github.com/hughperkins/DeepCL/blob/master/test/testlogicaloperators.cpp#L220

```
TEST( testlogicaloperators, Convolve_2layers_relu_Xor ) {
cout << "Xor, convolve" << endl;
...
```
You can run it like this:
```
deepcl_unittests tests=testlogicaloperators.Convolve_2layers_relu_Xor
```
https://gist.github.com/hughperkins/b13f07e553dea1b742dc73b6686f367e

**Comment by hughperkins** [comment]
Oh. python.... hmmm... ok, let me ponder that :-)

**Comment by hughperkins** [comment]
How does this look? https://github.com/hughperkins/DeepCL/blob/master/python/examples/xor.py

**Comment by d0znpp** [comment]
Great, thx!

**Comment by hughperkins** [comment]
Cool :-)

**Comment by hughperkins** [comment]
(Hmmm, seems `seed` is more complicted than setting the python-side seed. Pondering...)

**Comment by hughperkins** [comment]
(added seed method now `PyDeepCL.RandomSingleton.seed(some_seed_here)` https://github.com/hughperkins/DeepCL/blob/0092b0c57c65ca91ff174e2d6d32f91a1c2c5c7a/python/examples/xor.py#L33 )
