### ISSUE TITLE
Is it possible to use a rectangular matrix as input

### ISSUE THREAD

**Issue by NKUCodingCat** [hughperkins/DeepCL#81]
I read `NeuralNet.pyx` and it seems that I can use square image only, so is it possible to use an 
rectangular image ( like an image in 100*25 ) as input? 

Meanwhile, what does netdef string like `rt2-8c5z-relu-mp2-16c5z-relu-mp3-150n-tanh-10n` means? I worked out that mp is for pooling layer, 2 is the size and tanh is an activation layer.....and so on. However, it is hard to remember each abbreviation, so are there any document or memorandum about it, or they are just an convention I don't know? 

Anyway, thank you for answering my question.

**Comment by NKUCodingCat** [comment]
Well I found the meanings in Commandline.md...... How can I miss this doc=.=

**Comment by hughperkins** [comment]
As far as rectangular inputs ... you'd need to pad them to be square, for now.  There is a convolutional kernel implemented that handles rectangular inputs though, so it's not out of the bounds of possibility to modify deepcl to handle them, but I think joining a few images together, padded, into a single square image, might be quite a lot easier, for now?

**Comment by NKUCodingCat** [comment]
Well, padding to a square sounds reasonable ... but it may let performance down, whatever, I gonna to try  both of it, Thank you for your help.

**Comment by hughperkins** [comment]
Ok :-)
