### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by ihategribfiles** [hughperkins/DeepCL#89]
probably really silly issue:

windows 10
python 2.7.12 :: Anaconda 4.0.0 (64-bit)

deepcl_unittests results in '158 tests passed, 2 disabled tests'

pip install --pre DeepCL 
->

C:\Users\usr\Documents\deepcl_stuff\deepcl-win64-v11.3.1>pip install --pre DeepCL
Collecting DeepCL
  Using cached DeepCL-11.3.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\users\usr\anaconda2\lib\site-packages (from DeepCL)
Building wheels for collected packages: DeepCL
  Running setup.py bdist_wheel for DeepCL ... error
  Complete output from command c:\users\usr\anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\usr\\appdata\\local\\temp\\pip-build-jqvkfc\\DeepCL\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\usr\appdata\local\temp\tmpwln_ompip-wheel- --python-tag cp27:
  version:  11.3.1
  running bdist_wheel
  running build
  running build_ext
  building 'PyDeepCL' extension
  creating build
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  C:\TDM-GCC-64\bin\gcc.exe -DMS_WIN64 -mdll -O -Wall -Ic:\users\usr\anaconda2\include -Ic:\users\usr\anaconda2\PC -c PyDeepCL.cpp -o build\temp.win-amd64-2.7\Release\pydeepcl.o /EHsc -DUSE_CLEW
  gcc: error: /EHsc: No such file or directory
  error: command 'C:\\TDM-GCC-64\\bin\\gcc.exe' failed with exit status 1

  ----------------------------------------
  Failed building wheel for DeepCL
  Running setup.py clean for DeepCL
Failed to build DeepCL
Installing collected packages: DeepCL
  Running setup.py install for DeepCL ... error
    Complete output from command c:\users\usr\anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\usr\\appdata\\local\\temp\\pip-build-jqvkfc\\DeepCL\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\usr\appdata\local\temp\pip-ck5yzx-record\install-record.txt --single-version-externally-managed --compile:
    version:  11.3.1
    running install
    running build
    running build_ext
    building 'PyDeepCL' extension
    creating build
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    C:\TDM-GCC-64\bin\gcc.exe -DMS_WIN64 -mdll -O -Wall -Ic:\users\usr\anaconda2\include -Ic:\users\usr\anaconda2\PC -c PyDeepCL.cpp -o build\temp.win-amd64-2.7\Release\pydeepcl.o /EHsc -DUSE_CLEW
    gcc: error: /EHsc: No such file or directory
    error: command 'C:\\TDM-GCC-64\\bin\\gcc.exe' failed with exit status 1

    ----------------------------------------
Command "c:\users\usr\anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\usr\\appdata\\local\\temp\\pip-build-jqvkfc\\DeepCL\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\usr\appdata\local\temp\pip-ck5yzx-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\usr\appdata\local\temp\pip-build-jqvkfc\DeepCL\

C:\Users\usr\Documents\deepcl_stuff\deepcl-win64-v11.3.1>

**Comment by hughperkins** [comment]
Seems like it is using gcc ... on windows.... this is ... odd :-P  on windows, ie should be using something like `cl1.exe` to compile.  Actually, it shouldnt be compiling.  It should just pull downo prebuilt binaries.

Can you first try removing the `--pre` bit, and retry?  Can you confirm you're not using mingw, or cygwin, and not using a mingw/cygwin version of python?

Perhaps I will try anaconda 4, and see what happens.

**Comment by hughperkins** [comment]
(Can you maybe try downloading https://pypi.python.org/packages/00/bb/f2365ed5e89013bda5c9fd76b6de53e9e317d0def980105c705ae75315ee/DeepCL-11.3.1-py2.7-win-amd64.egg#md5=1da4eb1b8f2670dafe85695bdec64c67 directly, and trying to install that, and see wht happens?)

**Comment by ihategribfiles** [comment]
I tried without --pre and got the same output. 

my python version : '2.7.12 |Anaconda 4.0.0 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]'

Please excuse the ignorance, but how do i stall from the unzipped .egg files.

thanks so much!

**Comment by hughperkins** [comment]
Apparently, I should probalby be building wheels, rather than eggs, see https://github.com/pypa/pip/issues/492

With this in mind, can you first try:
```
pip install DeepCL-11.3.1-py2.7-win32.egg
```
If that doesnt work, cna you try:
```
wheel convert DeepCL-11.3.1-py2.7-win32.egg
dir *.whl
pip install [put the name of the .whl file here]
```
Whatever happens (success/fail), can you report back what you tried, and what happened?

**Comment by GermaVinsmoke** [comment]
Error

`DeepCL-11.3.1-py27-cp27-win_amd64.whl is not a supported wheel on this platform.`

I'm installing this in Python 2.7.13 virtual env and it's of 64 bit

**Comment by PhilipDeegan** [comment]
https://github.com/hughperkins/DeepCL/issues/148
