### ISSUE TITLE
Missing Requirements for build

### ISSUE THREAD

**Issue by blacky-i** [hughperkins/DeepCL#92]
For successful build for Ubuntu 14.04 also requires 
* gfortan (`sudo apt-get install gfortran`)
* boost library (http://www.boost.org/users/history/version_1_61_0.html)

This information was not mentioned in Readme

**Comment by hughperkins** [comment]
gfortran is mentioned in the Build.md at line 33? https://github.com/hughperkins/DeepCL/blob/master/doc/Build.md

I'm not entirely convinced boost is required, I think it just spews out warnings if not present, but builds ok?  (I'm like 70% sure of this, so if you're really sure it's required, I might spin up an ec2 instance, and check).

**Comment by blacky-i** [comment]
I have successfully built DeepCL on Ubuntu 14.04.
Boost library is required for clBLAS. Cmake is looking for installed Boost.
Yes, you right about gfortran, did not look it properly.

**Comment by hughperkins** [comment]
So, clblas kind of asks for it, but not sure it exactly *needs* it.  I just tried buliding deepcl from scratch, on a base ubuntu 14.04 ec2 box, and here is the full build, from ssh'ing into the terminal and running `script build.log`, on the base instance: https://gist.github.com/hughperkins/0478aacf0291efb65f04fdaec3b68df8

You can see I only install the following:

```
sudo apt-get install git cmake cmake-curses-gui gcc g++ gfortran htop wcalc
```
(htop and wcalc are just cos I like using them, not actually necessary for the install)

**Comment by blacky-i** [comment]
Strange. In my case bulid ended with error. 
 I will try to rebuild it without Boost today later.

**Comment by blacky-i** [comment]
Yes, you are right

**Comment by hughperkins** [comment]
Cool :-)
