### ISSUE TITLE
Requesting PNG support

### ISSUE THREAD

**Issue by merceyz** [hughperkins/DeepCL#96]
As per your request i'm opening a issue to request PNG support

**Comment by hughperkins** [comment]
There's already some code to write pngs, ie:

https://github.com/hughperkins/DeepCL/blob/master/src/util/ImagePng.h

libpng is currently in the 'maintainers options': https://github.com/hughperkins/DeepCL/blob/master/CMakeLists.txt#L26

```
if(MAINTAINER_OPTIONS)
    OPTION(BUILD_PYTHON_WRAPPERS "Build python wrappers.  Maintainers only." OFF.)
    OPTION(DEV_RUN_COG "DeepCL maintainers only, otherwise set to 'OFF'." OFF)
    OPTION(PROTOTYPING "Only for devs." OFF)
#    mark_as_advanced(FORCE PROTOTYPING)
    OPTION(LIBPNGPP_AVAILABLE "Some toys/samples only." OFF)
#    mark_as_advanced(FORCE LIBPNGPP_AVAILABLE)
else()
```
...but could be moved into the standard options list.

I dont have time to add this right now.  Perhaps this is something you could take a look at?

**Comment by merceyz** [comment]
I enabled the maintainers options, then the png box, it threw an error that it could not locate the files for it. It gave me no option to say where they are, it does with the jpeg one.

I guess i need a guide on how to build deepcl with libpng as well

**Comment by merceyz** [comment]
I ended up doing the same as i did in #85, do all the work in c# then just overwrite the memory of deepcl

**Comment by hughperkins** [comment]
Cool :-)
